version: "3.7"

services:
  db:
    image: postgres

    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=taskManager
    volumes:
      - pgdata:/data/postgres

  backend:
    restart: always
    environment:
      - SECRET=ad1a8a1bee5062581d3a6a1a29697514
      - PORT=3334
      - DATABASE_URL=postgresql://docker:docker@db:5432/taskManager?schema=public
    build: backend/.
    ports:
      - 3334:3334
    volumes:
      - .:/usr/app
    depends_on:
      - db
    links:
      - db
    

  frontend:
    restart: always
    build: frontend/.
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
volumes:
  pgdata:
    driver: local
